[package]
name = "calcit_dylib"
version = "0.0.3"
authors = ["jiyinyiyong <jiyinyiyong@gmail.com>"]
edition = "2024"

[lib]
name = "calcit_std"
path = "src/lib.rs"
crate-type = ["cdylib"] # Expose only the stable C-safe buffer ABI.


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cirru_edn = "0.8.0"
