on:
  push:
    branches:
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/calcit-lang/calcit/releases/download/0.8.9/cr'
          name: 'cr'
          version: '0.8.9'

      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/calcit-lang/calcit/releases/download/0.8.9/caps'
          name: 'caps'
          version: '0.8.9'

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - run: rm -rfv dylibs/* && mkdir dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: cr -1
