on:
  push:
    branches:
      - master
      - main
  pull_request: {}

name: Test

jobs:
  build_and_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: calcit-lang/setup-calcit@v1

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo build --release

      - run: cargo clippy

      - run: mkdir -p dylibs/ && ls target/release/ && cp -v target/release/*.* dylibs/

      - run: calcit calcit.cirru
